services:
  - type: web
    name: high-lines-backend
    env: python
    pythonVersion: 3.11
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /billing/config_check
    envVars:
      # --- Stripe (PROD) ---
      - key: STRIPE_SECRET_KEY
        value: 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
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_1007d3fd903c03e02856630fffb339df36087d96feee353a0c805cbe7b9f2829
        sync: false
      - key: STRIPE_PRICE_ID
        value: price_1SIph6GpRAmKti1Wzu8GiL45
        sync: false

      # --- CORS / Frontend routing ---
      - key: ALLOWED_ORIGINS             # comma-separated Streamlit app origins ONLY
        value: https://high-lines-nfl-players.streamlit.app,https://high-lines-nba-players.streamlit.app,https://high-lines-cfb-games.streamlit.app,https://high-lines-nhl-players.streamlit.app
      - key: DEFAULT_FRONTEND_URL        # single Streamlit board to return to after Stripe
        value: https://high-lines-nfl-players.streamlit.app

      # (compat with your .env.example; harmless if unused)
      - key: FRONTEND_URL
        value: https://high-lines-nfl-players.streamlit.app

      # --- Dev shim tokens (optional; keep for now) ---
      - key: JWT_SECRET                  # any strong random string
        sync: false
      - key: JWT_ISSUER
        value: tail-wing-backend
      - key: TOKEN_TTL_MIN               # minutes (e.g., 10080 = 7 days)
        value: "10080"

      # --- Free users / whitelist (either one; both included for compatibility) ---
      - key: WHITELISTED_EMAILS          # comma-separated emails
        value: friend1@example.com,friend2@example.com
      - key: FREE_USERS                  # matches your .env.example naming
        value: friend1@example.com,friend2@example.com

      # --- Optional / informational (not required by backend; include only if you actually use it) ---
      - key: APP_URL                     # usually not needed; Render assigns URL dynamically
        value: https://high-lines-backend.onrender.com
