services:
  - type: web
    name: high-lines-backend
    env: python
    pythonVersion: 3.11
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://high-lines-nfl-players.streamlit.app,https://high-lines-nba-players.streamlit.app,https://high-lines-cfb_games.streamlit.app,https://high-lines-nhl-players.streamlit.app,https://high-lines.com
      - key: DEFAULT_FRONTEND_URL
        value: https://high-lines-nfl-players.streamlit.app
      - key: WHITELISTED_EMAILS
        sync: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /billing/config_check
