services:
  - type: web
    name: tailwing-backend
    env: python
    pythonVersion: 3.11
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://app.tailwing.xyz
      - key: ALLOWED_ORIGINS
        value: https://app.tailwing.xyz
      - key: WHITELISTED_EMAILS
        sync: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /billing/config_check
